aboutuser/urls.py
from django.urls import path

from . import views

app_name = 'aboutuser'

urlpatterns = [
    path('profil/', views.profil, name='profil'),
    path('review/<str:idtransaksi>/', views.review, name='review'),
    path('data/myreview/', views.dataMyReview, name='dataMyReview'),

]

autentikasi/urls.py
from django.urls import path

from . import views

app_name = 'autentikasi'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('filterPencarian', views.filterPencarian, name='filterPencarian'),
    path('data/basedOnReservasi/', views.data_basedOnReservasi, name='data_basedOnReservasi'),
    path('random', views.random, name='random'),
]

panpacation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('detail/', include('detail.urls')),
    path('pembayaran/', include('pembayaran.urls')),
    path('', include('autentikasi.urls')),
    path('', include('feeds.urls')),
    path('', include('aboutuser.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- BOOTSTRAP -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <link rel="icon" href="https://i.ibb.co/LCt8m8W/Group-555.png" style= "height:40px;width: 40px;" type="image/x-icon">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
      
        <!-- <link rel="shortcut icon" type="image/jpg" href="{% static 'img/Logo.png' %}"/> -->
        {% block style %}
        {% endblock style %}
      </head>
      
    <body>
        {% include 'navbar.html' %}
        {% block content %}{% endblock content %}

        <!-- Optional JavaScript -->
        {% block js %}{% endblock js %}
        <noscript>Your browser does not support JavaScript!</noscript>
    </body>
</html>

templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- Custom CSS -->
        {% block css %}{% endblock css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}" /> 
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css" />
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
            crossorigin="anonymous"
        />

        

        <link href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" rel="stylesheet">
        <script src="https://kit.fontawesome.com/c30424fd64.js" crossorigin="anonymous"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB_1QWeLKvKxKOmOt0tE2upLCOxueA2HTI"></script>      

        <title>{% block title %}{% endblock title %}</title>        
        
    </head>
    <body style="background-color: #F7F4F4;">
        {% include 'navbar.html' %}
        {% block content %}{% endblock content %}

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
        
        <!-- Optional JavaScript -->  
        {% block js %}{% endblock js %}
        <noscript>Your browser does not support JavaScript!</noscript>
    </body>
</html>

templates/messages.html
{% if messages %}
    <ul class="messages container mt-4 mb-0" style="list-style: none;">
        {% for message in messages %}
        {% if message.tags == "error" %} <li  class="alert alert-danger alert-dismissible fade show" >
        {% else %} <li  class="alert alert-{{ message.tags }} alert-dismissible fade show" >{% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
{% endif %}

templates/navbar.html
<div class="navigation-wrap bg-light start-header start-style">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-md navbar-light" style="height: 70px;">
          <a class="navbar-brand mt-3" href="{% url 'main:main'%}"><img src="https://i.ibb.co/mHMYYgg/Group-596-2.png" alt="LOGO-PANPACATION" border="0"></a>	

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          {% if is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto py-4 py-md-0">
              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="{% url 'main:main'%}">Homepage</a>
              </li>
              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="{% url 'aboutuser:profil'%}">Profil</a>
              </li>
              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="{% url 'autentikasi:logout'%}">Log out</a>
              </li>
              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="#">|</a>
              </li>
              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="#">Hallo, {{nama_depan}}</a>
              </li>
            </ul>
          </div>

          {%else%}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto py-4 py-md-0">

              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="{% url 'autentikasi:register'%}">Register</a>
              </li>
              <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                <a class="nav-link" href="{% url 'autentikasi:login'%}">Login</a>
              </li>
            </ul>
          </div>
          {%endif%}
          
        </nav>		
      </div>
    </div>
  </div>
</div>