aboutuser/urls.py
from django.urls import path

from . import views

app_name = 'aboutuser'

urlpatterns = [
    path('profil/', views.profil, name='profil'),
    path('review/<str:idtransaksi>/', views.review, name='review'),
    path('data/myreview/', views.dataMyReview, name='dataMyReview'),

]

autentikasi/urls.py
from django.urls import path

from . import views

app_name = 'autentikasi'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('filterPencarian', views.filterPencarian, name='filterPencarian'),
    path('data/basedOnReservasi/', views.data_basedOnReservasi, name='data_basedOnReservasi'),
    path('random', views.random, name='random'),
]

panpacation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('detail/', include('detail.urls')),
    path('pembayaran/', include('pembayaran.urls')),
    path('', include('autentikasi.urls')),
    path('', include('feeds.urls')),
    path('', include('aboutuser.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.shortcuts import render
from django.http import JsonResponse, Http404

def set_session(request, response):
    response['is_authenticated'] = request.session.get('is_authenticated')
    response['username'] = request.session.get('username')
    response['nama_depan'] = request.session.get('nama_depan')
    response['nama_belakang'] = request.session.get('nama_belakang')

def main(request):
    response = {}
    set_session(request, response)

    return render(request, 'main/main.html', response)

def filterPencarian(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect('/login/')
    response = {}
    set_session(request, response)

    if (request.method == 'POST'):
        check_in = request.POST.get('check_in')
        check_in = str(check_in) + ' 00:00:00'
        check_out = request.POST.get('check_out')
        check_out = str(check_out) + ' 00:00:00'
        reservasi = request.POST.get('reservasi')
        lokasi = request.POST.get('lokasi')
        jumlah = request.POST.get('jumlah')

        if (check_in > check_out):
            return redirect('/')
        print(check_in)
        print(check_out)
        print(check_out > check_in)
        print(lokasi)

        return redirect('/detail/'+ check_in + '/' + check_out + '/' + reservasi + '/' + lokasi + '/' + jumlah + '/')
    return ('/')


def data_basedOnReservasi(request):
    if request.method == "POST":
        selected_reservasi = request.POST.get("selected_reservasi")
        print(selected_reservasi)
        
        if(selected_reservasi == 'Villa'):
            stmt = '''
            SELECT distinct T.provinsi
            FROM TEMPAT_PENGINAPAN T, VILLA V
            WHERE T.id_penginapan = V.id_penginapan;
            '''
        elif(selected_reservasi == 'Apartemen'):
            stmt = '''
            SELECT distinct T.provinsi
            FROM TEMPAT_PENGINAPAN T, APARTEMEN A
            WHERE T.id_penginapan = A.id_penginapan;
            '''
        else:
            stmt = '''
            SELECT distinct T.provinsi
            FROM TEMPAT_PENGINAPAN T, KOS K
            WHERE T.id_penginapan = K.id_penginapan;
            '''
        
        with connection.cursor() as cursor:
            cursor.execute(stmt)
            listOfKota = cursor.fetchall()
        print(listOfKota)

    return JsonResponse({'listKota' : listOfKota})

def random(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect('/login/')
    response = {}
    set_session(request, response)
    return render(request, 'main/randomDesti.html', response)
    

main/templates/main/main.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
<title> Homepage </title>
{%endblock style%}

{% block content %}
<section id="jumbotron">
    <header>
        <div id="indicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#indicators" data-slide-to="0" class="active"></li>
                <li data-target="#indicators" data-slide-to="1"></li>
                <li data-target="#indicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div id="header1" class="carousel-item active">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div> <!-- Slide Two - Set the background image for this slide in the line below -->
                <div id="header2" class="carousel-item">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div> <!-- Slide Three - Set the background image for this slide in the line below -->
                <div id="header3" class="carousel-item">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
            </div> <a class="carousel-control-prev" href="#indicators" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a> <a class="carousel-control-next" href="#indicators" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
        </div>
    </header>

</section>

<section id="homepage-form">
    <div class="container d-flex justify-content-center align-items-center card shadow" id="container-form-homepage">
        <form class="homepage-form" action="{% url 'main:filterPencarian'%}" method="POST">
            {% csrf_token %}
            <h2 class="font-weight-light text-center mb-5"> Mau staycation kemana? </h2>
            <div class="row">
              <div class="col">
                <label>Check In:</label>
                <input type="date" class="form-control" placeholder="Check In" name="check_in" required>
              </div>
              <div class="col">
                <label>Check Out:</label>
                <input type="date" class="form-control" placeholder="Check Out" name="check_out" required>
              </div>
              <div class="col">
                <label>Reservasi: </label>
                <select class="form-control" name="reservasi" id="select-reservasi" required>
                    <option value="">Pilih Reservasi</option>
                    <option value="Apartemen">Apartemen</option>
                    <option value="Villa">Villa</option>
                    <option value="Kost">Kost</option>
                </select>
              </div>
              <div class="col">
                <label>Lokasi: </label>
                <select class="form-control" name="lokasi" id="select-lokasi" required>
                    <option value="">Pilih Provinsi</option>
                </select>
              </div>
              <div class="col">
                <label>Jumlah: </label>
                <input type="text" class="form-control" placeholder="3" name="jumlah" required>
              </div>
            </div>
            <div class="d-flex justify-content-end align-items-start">
                <button id="button-check-ketersediaan" type="submit" class="mt-5 btn btn-light">Check Ketersediaan</button>
            </div>
        </form>
    </div>
</section>

<section id="pilihan-navigasi" class="p-4">
    <div class="col justify-content-center align-items-center">
        <h5 class="text-center">Fasilitas Reservasi</h5>
        <hr>
        <div class="row row-cols-1 row-cols-md-3 g-4 mb-5" id="list-reservasi">
            <div class="col mt-5">
                <a href="/detail/apartemen/">
                    <img id="foto-pilih-navigasi" src="{% static 'main/img/Hotel.png' %}" class="card-img" alt="..."/>
                    <div class="centered">Apartemen</div>
                </a>
            </div>
            <div class="col mt-5">
                <a href="/detail/villa/">
                    <img id="foto-pilih-navigasi" src="{% static 'main/img/Villa.png' %}" class="card-img" alt="..."/>
                    <div class="centered">Villa</div>
                </a>
            </div>
            <div class="col mt-5">
                <a href="/detail/kost/">
                    <img id="foto-pilih-navigasi" src="{% static 'main/img/Kost.png' %}" class="card-img" alt="..."/>
                    <div class="centered">Kost</div>
                </a>
            </div>
        </div>
    </div>
</section>

<section id="service">
    <div class="lightbox-gallery">
        <div class="container">
            <div class="row photos card col">
                <h5 class="text-center mt-5">Layanan yang Kami Tawarkan</h5>
                <hr>
                <div class="row">
                    <div class="col-sm-6 col-md-4 col-lg-3 item">
                        <img class="img-fluid" src="{% static 'main/img/TestCovid.png' %}">
                        <p>Test Covid</p>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-3 item">
                        <img class="img-fluid" src="{% static 'main/img/NearHotel.png' %}">
                        <p>Near Penginapan</p>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-3 item">
                        <img class="img-fluid" src="{% static 'main/img/MudahReservasi.png' %}">
                        <p>Kemudahan Reservasi</p>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-3 item ">
                        <img class="img-fluid" src="{% static 'main/img/Diskon.png' %}">
                        <p>Promo Special</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<footer>
    <div class="row justify-content-center mb-0 pt-5 pb-0 row-2 px-3">
        <div class="col-12">
            <div class="row row-2">
                <div class="col-sm-3 text-md-center">
                    <h5><span> <i class="fa fa-firefox text-light" aria-hidden="true"></i></span><b>Panpacation</b></h5>
                </div>
                <div class="col-sm-3 my-sm-0 mt-5">
                    <ul class="list-unstyled">
                        <a href="#pilihan-navigasi">
                            <li class="mt-0">Villa</li>
                        </a>
                        <a href="#pilihan-navigasi">
                            <li>Kost</li>
                        </a>
                        <a href="#pilihan-navigasi">
                            <li>Apartemen</li>
                        </a>
                    </ul>
                </div>
                <div class="col-sm-3 my-sm-0 mt-5">
                    <ul class="list-unstyled">
                        <a href="#service">
                            <li class="mt-0">Test Covid</li>
                        </a>
                        <a href="#service">
                            <li>Near Penginapan</li>
                        </a>
                        <a href="#service">
                            <li>Kemudahan Reservasi</li>
                        </a>
                        <a href="#service">
                            <li>Promo Special</li>
                        </a>
                    </ul>
                </div>
                <div class="col-sm-3 my-sm-0 mt-5">
                    <ul class="list-unstyled">
                        <a href="{% url 'aboutuser:profil'%}">
                            <li class="mt-0">Profil</li>
                        </a>
                        <a href="{% url 'autentikasi:login'%}">
                            <li>Log In</li>
                        </a>
                        <a href="{% url 'autentikasi:register'%}">
                            <li>Register</li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center mt-0 pt-0 row-1 mb-0 px-sm-3 px-2">
        <div class="col-12">
            <div class="row my-4 row-1 no-gutters">
                <div class="col-sm-3 col-auto text-center"><small>&#9400; Panpacation</small></div>
                <div class="col-md-3 col-auto "></div>
                <div class="col-md-3 col-auto"></div>
                <div class="col my-auto text-md-left text-right "> <small> panpacation@gmail.com <span><img src="https://i.imgur.com/TtB6MDc.png" class="img-fluid " width="25"></span> <span><img src="https://i.imgur.com/N90KDYM.png" class="img-fluid " width="25"></span></small> </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'main/javascript/main.js' %}" type="text/javascript"></script>
{% endblock content %}

main/templates/main/randomDesti.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
<title> Homepage </title>
{%endblock style%}

{% block content %}

<section id="random">
    <div class="container">
        <div class="card mx-auto" id="card-random">
            <div class="card-body">
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <h2 class="font-weight-light text-center mb-5"> Mau staycation kemana? </h2>
                        <div class="row align-items-center justify-content-center">
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior1.png' %}">
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior2.png' %}">
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior3.png' %}">
                            </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <h2 class="font-weight-light text-center mb-5"> Mau staycation kemana? </h2>
                        <div class="row align-items-center justify-content-center">
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior4.png' %}">
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior5.png' %}">
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior6.png' %}">
                            </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <h2 class="font-weight-light text-center mb-5"> Mau staycation kemana? </h2>
                        <div class="row align-items-center justify-content-center">
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior7.png' %}">
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior8.png' %}">
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-3 item">
                                <img class="img-diklik img-fluid" src="{% static 'main/img/Interior9.png' %}">
                            </div>
                        </div>
                      </div>
                    </div>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <button id="button-random" type="submit" class="mt-5 btn btn-light" data-toggle="collapse" href="#home">Next</button>
                    </a>
                  </div>
                <form>
                    <input type="hidden" id="keep-random-no" value="">
                </form>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'main/javascript/main.js' %}" type="text/javascript"></script>
{% endblock content %}