aboutuser/urls.py
from django.urls import path

from . import views

app_name = 'aboutuser'

urlpatterns = [
    path('profil/', views.profil, name='profil'),
    path('review/<str:idtransaksi>/', views.review, name='review'),
    path('data/myreview/', views.dataMyReview, name='dataMyReview'),

]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
    path('filterPencarian', views.filterPencarian, name='filterPencarian'),
    path('data/basedOnReservasi/', views.data_basedOnReservasi, name='data_basedOnReservasi'),
    path('random', views.random, name='random'),
]

panpacation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('detail/', include('detail.urls')),
    path('pembayaran/', include('pembayaran.urls')),
    path('', include('autentikasi.urls')),
    path('', include('feeds.urls')),
    path('', include('aboutuser.urls')),
]

aboutuser/models.py
from django.db import models

# Create your models here.

aboutuser/views.py
from django.shortcuts import render, redirect
from django.db import connection
from django.shortcuts import render
from django.http import JsonResponse, Http404
from datetime import datetime

def set_session(request, response):
    response['is_authenticated'] = request.session.get('is_authenticated')
    response['username'] = request.session.get('username')
    response['nama_depan'] = request.session.get('nama_depan')
    response['nama_belakang'] = request.session.get('nama_belakang')

def profil(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect('/login/')
    response = {}
    set_session(request, response)

    stmt1 = '''
    SELECT distinct T.id_transaksi, T.total_bayar, TP.tgl_checkin, TP.tgl_checkout, TE.nama, TE.provinsi, F.link
    FROM TRANSAKSI T, TRANSAKSI_PENGINAPAN TP, PILIHAN_KOS_ROOM PKR, KOS_ROOM KR, KOS K, TEMPAT_PENGINAPAN TE, FOTO F
    WHERE T.pengguna = %s AND T.id_transaksi = TP.id_transaksi AND TP.id_transaksi_penginapan = PKR.id_transaksi_penginapan AND PKR.id_kos = KR.id_kos AND KR.id_kos = K.id_penginapan AND K.id_penginapan = TE.id_penginapan AND TE.id_penginapan = F.id_penginapan;
    '''

    stmt2 = '''
    SELECT distinct T.id_transaksi, T.total_bayar, TP.tgl_checkin, TP.tgl_checkout, TE.nama, TE.provinsi, F.link
    FROM TRANSAKSI T, TRANSAKSI_PENGINAPAN TP, PILIHAN_APARTEMEN_ROOM PAR, APARTEMEN_ROOM AR, APARTEMEN A, TEMPAT_PENGINAPAN TE, FOTO F
    WHERE T.pengguna = %s AND T.id_transaksi = TP.id_transaksi AND TP.id_transaksi_penginapan = PAR.id_transaksi_penginapan AND PAR.id_apartemen = AR.id_apartemen AND AR.id_apartemen = A.id_penginapan AND A.id_penginapan = TE.id_penginapan AND TE.id_penginapan = F.id_penginapan;
    '''

    stmt3 = '''
    SELECT distinct T.id_transaksi, T.total_bayar, TP.tgl_checkin, TP.tgl_checkout, TE.nama, TE.provinsi, F.link
    FROM TRANSAKSI T, TRANSAKSI_PENGINAPAN TP, PILIHAN_VILLA PV, VILLA V, TEMPAT_PENGINAPAN TE, FOTO F
    WHERE T.pengguna = %s AND T.id_transaksi = TP.id_transaksi AND TP.id_transaksi_penginapan = PV.id_transaksi_penginapan AND PV.id_villa = V.id_penginapan AND V.id_penginapan = TE.id_penginapan AND TE.id_penginapan = F.id_penginapan;
    '''
    try:
        with connection.cursor() as cursor:
            cursor.execute(stmt1, [request.session.get('username')])
            listTransaksiKos = cursor.fetchall()
        with connection.cursor() as cursor:
            cursor.execute(stmt2, [request.session.get('username')])
            listTransaksiApart = cursor.fetchall() 
        with connection.cursor() as cursor:
            cursor.execute(stmt3, [request.session.get('username')])
            listTransaksiVilla = cursor.fetchall()
        response['listTransaksi'] = listTransaksiKos + listTransaksiApart + listTransaksiVilla
    except:
        response['error'] = 'ada suatu kesalahan'

    return render(request, 'aboutuser/profil.html', response)

def review(request, idtransaksi):
    if (not(request.session.get('is_authenticated'))):
        return redirect('/login/')
    response = {}
    set_session(request, response)

    if request.method == "POST":
        print("masuk post")
        stmt1 = '''
        SELECT TP.id_transaksi_penginapan FROM TRANSAKSI_PENGINAPAN TP, TRANSAKSI T WHERE T.id_transaksi = TP.id_transaksi AND T.id_transaksi = %s;
        '''
        
        with connection.cursor() as cursor:
            cursor.execute(stmt1, [idtransaksi])
            idTransaksiPenginapan = cursor.fetchall()
        idTransaksiPenginapan = idTransaksiPenginapan[0][0]
        print(idTransaksiPenginapan)

        stmt2 = '''
        INSERT INTO REVIEW (pengguna, waktu, id_transaksi_penginapan, isi, rating)
        VALUES (%s,%s,%s,%s,%s);
        '''

        try:
            pengguna = request.session.get('username')
            now = datetime.now()
            dt_string = now.strftime("%Y-%m-%d %H:%M:%S")
            waktu = dt_string
            isi = request.POST.get('reviewIsi')
            rating = request.POST.get('rating')
            print(pengguna)
            print(waktu)
            print(isi)
            print(rating)
            with connection.cursor() as cursor:
                cursor.execute(stmt2, [pengguna, waktu, idTransaksiPenginapan, isi, rating])
                connection.commit()
            return redirect('/profil/')
        except:
            response['error'] = 'ada suatu kesalahan'
    
    return redirect('/profil/')

def dataMyReview(request):
    if (not(request.session.get('is_authenticated'))):
        return redirect('/login/')
    response = {}
    set_session(request, response)

    if request.method == "POST":
        id_transaksi = request.POST.get("id_transaksi")

        stmt1 = '''
        SELECT TP.id_transaksi_penginapan FROM TRANSAKSI_PENGINAPAN TP, TRANSAKSI T WHERE T.id_transaksi = TP.id_transaksi AND T.id_transaksi = %s;
        '''
        
        with connection.cursor() as cursor:
            cursor.execute(stmt1, [id_transaksi])
            idTransaksiPenginapan = cursor.fetchall()
        idTransaksiPenginapan = idTransaksiPenginapan[0][0]
        print(idTransaksiPenginapan)
    
        stmt2 = '''
        SELECT R.isi, R.rating FROM REVIEW R WHERE R.pengguna = %s AND R.id_transaksi_penginapan = %s;
        '''
        try:
            pengguna = request.session.get('username')
            with connection.cursor() as cursor:
                cursor.execute(stmt2, [pengguna, idTransaksiPenginapan])
                myreview = cursor.fetchall()
            print(myreview)
            return JsonResponse({"listMyReview" : myreview})
        except:
            response['error'] = 'ada suatu kesalahan'

    return redirect('/profil/')

aboutuser/templates/aboutuser/profil.html
{% extends 'base.html' %}
{% load static %}

{%block style%}
<link rel="stylesheet" href="{% static 'aboutuser/css/aboutuser.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<title> Register </title>
{%endblock style%}

{% block content %}
<section id="header">
    <div class="header-feeds">
    </div>
</section>

<section id="profil">
    <div class="main-panel">
        <div class="container">
            <div class="d-flex flex-row justify-content-center align-items-start">

                <!-- BAR PROFILE -->
                <div class="col-md-4 grid-margin stretch-card">
                    <div class="card">
                        <div class="profile-card">

                            <div class="profile-header">
                                <div class="user-image">
                                    <img src="https://i.ibb.co/BV8cBqm/Group-597.png" class="img ">
                                </div>
                            </div>

                            <div class="profile-content">
                                <div class="profile-name">{{nama_depan}} {{nama_belakang}}</div>
                                <div class="profile-designation">{{username}}</div>
                                <ul class="profile-info-list">
                                    <a href="{% url 'main:main'%}" class="profile-info-list-item"><i class="mdi mdi-eye"></i>Homepage</a>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- BAR PROFILE -->

                <!-- BAR KANAN -->
                <div class="col-md-6 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            <div class="container">
                                <ul class="nav nav-tabs" role="tablist">
                                    <!-- CONTROL SUB NAVBAR -->
                                    <li class="nav-item">
                                        <a id="nav-listPesanan" class="nav-link active" data-toggle="tab" href="#home">
                                            <div class="col">
                                                <h6 class="font-weight-light">List Pesanan</h6>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a id="nav-listPesanan" class="nav-link" data-toggle="tab" href="#menu1">
                                            <div class="col">
                                                <h6 class="font-weight-light">Review</h6>
                                            </div>
                                        </a>
                                    </li>
                                    <!-- CONTROL SUB NAVBAR -->
                                </ul>
                        
                                <!-- KONTEN SUB NAVBAR -->
                                <div class="tab-content">

                                    <!-- LIST PESANAN -->
                                    <div id="home" class="container tab-pane active"><br>
                                        <div class="d-flex justify-content-left align-items-center">
                                            <h6>List Pesanan Anda</h6>
                                        </div>
                                        {% for transaksi in listTransaksi %}
                                        <div class="card" width="100%">
                                            <div class="row no-gutters">
                                              <div class="col-md-4 card-body d-flex justify-content-center align-items-start">
                                                <img id="foto-list-pesan" src="{{transaksi.6}}" class="card-img" alt="...">
                                              </div>
                                              <div class="col-md-8">
                                                <div class="card-body">
                                                  <h6 class="card-title">{{transaksi.4}}</h6>
                                                  <h6 class="font-weight-light" style="font-size: 12px;">{{transaksi.5}}</h6>
                                                  <div>
                                                      <p id="text-list-pesan" class="text-left">Id Transaksi: {{transaksi.0}}</p>
                                                      <p id="text-list-pesan" class="text-left">Check In: {{transaksi.2}}</p>
                                                      <p id="text-list-pesan" class="text-left">Check Out: {{transaksi.3}}</p>
                                                  </div>
                                                  <div class="d-flex justify-content-right align-items-end mt-3">
                                                    <label id="label-harga">Rp. {{transaksi.1}}</label>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                        </div>
                                        {%endfor%}
                                    </div>
                                    <!-- LIST PESANAN -->

                                    <!-- REVIEW -->
                                    <div id="menu1" class="container tab-pane fade"><br>
                                        <div class="d-flex justify-content-left align-items-center">
                                            <h6>Review Pesanan Anda</h6>
                                        </div>
                                        {% for transaksi in listTransaksi %}
                                        <div class="card col" width="100%">

                                            <div class="row no-gutters">
                                              <div class="col-md-4 card-body d-flex justify-content-center align-items-start">
                                                <img id="foto-list-pesan" src="{{transaksi.6}}" class="card-img" alt="...">
                                              </div>

                                              <div class="col-md-8">
                                                <div class="card-body">
                                                    <h6 class="card-title">{{transaksi.4}}</h6>
                                                    <h6 class="font-weight-light" style="font-size: 12px;">{{transaksi.5}}</h6>
                                                    <div>
                                                        <p id="text-list-pesan" class="text-left">Id Transaksi: {{transaksi.0}}</p>
                                                        <button id="button-review" value="{{transaksi.0}}" type="button" class="mt-5 btn btn-light" data-toggle="collapse" data-target="#collapseExample{{transaksi.0}}" aria-expanded="false" aria-controls="collapseExample{{transaksi.0}}">Create Review</button>
                                                        <button id="button-review" value="{{transaksi.0}}" type="button" class="button-review mt-5 btn btn-light" data-toggle="collapse" data-target="#collapseExample2{{transaksi.0}}" aria-expanded="false" aria-controls="collapseExample2">My Review</button>
                                                    </div>
                                                </div>
                                              </div>
                                            </div>

                                            <div class="collapse" id="collapseExample{{transaksi.0}}">
                                                <!-- STAR -->
                                                <div class="container d-flex justify-content-center align-items-center">
                                                    <div class="row">
                                                        <div class="col">
                                                            <div class="" style="width: max-content;">
                                                                <div class="text-center">
                                                                    <form action="{% url 'aboutuser:review' transaksi.0 %}" method="POST">
                                                                        {% csrf_token %}
                                                                        <h6 class="mt-1">Rate us</h6>
                                                                        <div class="rating"> 
                                                                            <input type="radio" name="rating" value="5" id="5{{transaksi.0}}">
                                                                            <label id="star" for="5{{transaksi.0}}">☆</label> 
                                                                            <input type="radio" name="rating" value="4" id="4{{transaksi.0}}">
                                                                            <label id="star" for="4{{transaksi.0}}">☆</label> 
                                                                            <input type="radio" name="rating" value="3" id="3{{transaksi.0}}">
                                                                            <label id="star" for="3{{transaksi.0}}">☆</label> 
                                                                            <input type="radio" name="rating" value="2" id="2{{transaksi.0}}">
                                                                            <label id="star" for="2{{transaksi.0}}">☆</label> 
                                                                            <input type="radio" name="rating" value="1{{transaksi.0}}" id="1">
                                                                            <label id="star" for="1{{transaksi.0}}">☆</label>
                                                                        </div>
                                                                        <input type="text" class="form-control" style="height:100px" name="reviewIsi">
                                                                        <button id="button-review" type="submit" class="mt-5 btn btn-light">Submit</button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- STAR -->
                                            </div>

                                            <div class="collapse my-review" id="collapseExample2{{transaksi.0}}">

                                            </div>

                                        </div>
                                            
                                        {%endfor%}
                                    </div>
                                    <!-- REVIEW -->
                                    
                                </div>
                                <!-- KONTEN SUB NAVBAR -->
                            </div>
                            
                        </div>
                    </div>
                </div>
                <!-- BAR KANAN -->

            </div>
        </div>
    </div>
</section>

<script src="{% static 'aboutuser/javascript/aboutuser.js' %}" type="text/javascript"></script>
{% endblock content %}